site_name: PCAM-24 Specification
site_url: https://greyforgelabs.github.io/pcam-24/
site_author: Greyforge Labs
copyright: Copyright &copy; 2026 Greyforge Labs

theme:
  name: material
  palette: 
    scheme: slate 
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

nav:
  - What is PCAM-24?: index.md
  - PCAM-24 Whitepaper: whitepaper.md
  - Formal Specification: spec.md
  - Designer Guide: guide.md
  - Minimal Example: minimal-example.md
  - Why not Time?: why-not-time.md
  - FAQ: faq.md
  - License: LICENSE.md
  - Audit: audit.md
